import tkinter 
import pymysql
from tkinter import * 
from tkinter import messagebox
from tkinter import ttk
t=tkinter.Tk()
t.geometry("600x600")
def findstore():
    db=pymysql.connect(host = "Localhost", user = "root", password = "root",database = "ims")
    cur=db.cursor()
    xcb=int(cb.get())
    sql="select name,address,city,phoneNo,regNo from store where storeid = %d"%(xcb)
    cur.execute(sql)
    db.commit()
    data = cur.fetchone()
    db.close()
    messagebox.showinfo("Hi there","Found Data From Store Table:" + str(xcb))
    e2.insert(0,data[0]) 
    e3.insert(0,data[1])
    e4.insert(0,data[2])
    e5.insert(0,data[3])
    e6.insert(0,str(data[4]))
def showstoreid():
    db=pymysql.connect(host = "Localhost", user = "root", password = "root",database = "ims")
    cur=db.cursor()
    sql = "select storeid from store "
    cur.execute(sql)
    data = cur.fetchall()
    lst=[]
    for i in data:
        lst.append(i[0])
    db.close()
    cb["values"] = lst
    
def updatestore():
    db=pymysql.connect(host = "Localhost", user = "root", password = "root",database = "ims")
    cur=db.cursor()
    xcb=int(cb.get())
    xb = e2.get()
    xc = e3.get()
    xd = e4.get()
    xe = e5.get()
    xf = int(e6.get())
    sql = "update store set name = '%s',address = '%s', city = '%s',phoneNo= '%s',regNo = %d where storeid =%d"%(xb,xc,xd,xe,xf,xcb)
    cur.execute(sql)
    db.commit()
    db.close()
    messagebox.showinfo("Hi There","Data Updated From Store Table:"+str(xcb))
    cb.delete(0,100)
    e2.delete(0,100)
    e3.delete(0,100)
    e4.delete(0,100)
    e5.delete(0,100)
    e6.delete(0,100)
def nw():
    cb.delete(0,100)
    e2.delete(0,100)
    e3.delete(0,100)
    e4.delete(0,100)
    e5.delete(0,100)
    e6.delete(0,100)
def btclose():
    t.destroy()
s=Canvas(t,width=600,  height = 60, bg = "green")
s.place(x=0,y=0)
s.create_text(290,30, text = "Find And Update Data From Store Table" , font= ("Times New Roman", 14, "bold"))

a=Label(t,text = "Store ID",font = ("Times New Roman",14,"bold"))
a.place(x=100,y=100)
cb=ttk.Combobox(t,width=20)
cb.place(x=295,y=105)
showstoreid()
b=Label(t,text = "Name",font = ("Times New Roman",14,"bold"))
b.place(x=100,y=150)
e2=Entry(t,width=20)
e2.place(x=300,y=155)
c=Label(t,text = "Address",font = ("Times New Roman",14,"bold"))
c.place(x=100,y=205)
e3=Entry(t,width=20)
e3.place(x=300,y=210)
d=Label(t,text = "City",font = ("Times New Roman",14,"bold"))
d.place(x=100,y=255)
e4=Entry(t,width=20)
e4.place(x=300,y=260)
e=Label(t,text = "Phone No",font = ("Times New Roman",14,"bold"))
e.place(x=100,y=310)
e5=Entry(t,width=20)
e5.place(x=300,y=315)
f=Label(t,text = "Registration No",font = ("Times New Roman",14,"bold"))
f.place(x=100,y=370)
e6=Entry(t,width=20)
e6.place(x=300,y=375)
bt=Button(t,text = "Find",fg="blue", command = findstore)
bt.place(x=100,y=500)
bt2=Button(t,text = "Close",fg = "red", command = btclose)
bt2.place(x=400,y=500)
bt3=Button(t,text = "Update",fg = "Green",command = updatestore)
bt3.place(x=200,y=500)
bt4=Button(t,text = "New",fg = "black",command = nw)
bt4.place(x=300,y=500)
t.mainloop()
